#!/usr/bin/env python3
"""Regenerate PROVENANCE.md by reading the disk."""
import hashlib, subprocess
from pathlib import Path

HERE = Path(__file__).resolve().parent
SRC = HERE.parent / "elena_replication"
EL = HERE.parent / "elena"
SKIP_DIRS = {"logs", "step1", "step2", "masks_by_chrom", "test_native",
             "power_control", "complement", "__pycache__"}

def digest(p, cap=64 * 1024 * 1024):
    h = hashlib.sha256()
    with open(p, "rb") as fh:
        while chunk := fh.read(1 << 20):
            h.update(chunk)
            if fh.tell() > cap:
                break
    return h.hexdigest()[:12]

def walk(root):
    for p in sorted(root.rglob("*")):
        if not p.is_file() or p.name == ".gitkeep":
            continue
        if SKIP_DIRS & set(p.relative_to(HERE).parts):
            continue
        yield p

# Only these paths were copied. Everything else under them was built here, and
# a first version of this script mislabelled phase_5/results/FINDINGS.md as an
# annotated copy purely because a file of the same name exists upstream.
COPIED_ROOTS = ["phase_2/results", "phase_2/scripts", "phase_2/data",
                "phase_3/data", "phase_3/scripts",
                "phase_4/scripts", "phase_5/scripts"]

out = []
w = out.append
w("# Provenance\n")
w("Which files were copied into this folder rather than produced in it, and the verification")
w("that they arrived intact. Generated by `scripts_provenance.py` reading the disk.\n")
sha = subprocess.run(["git", "rev-parse", "--short", "HEAD"],
                     capture_output=True, text=True).stdout.strip()
w(f"**Commit at generation:** `{sha}`\n")
w("SHA-256 over the first 64 MB. The artifacts SAIGE consumes were additionally compared byte for")
w("byte with `cmp`. MD5 is unavailable on this host, which runs in FIPS mode. Logs and bulk")
w("intermediates are excluded; what is listed is what a reader would want to trust.\n")
w("**`annotated` is not a failure.** Two inherited FINDINGS files carry a banner added here, saying")
w("they describe the replication's audit rather than this analysis. Content below the banner is")
w("untouched.\n")
w("---\n")

GROUPS = [
    ("Phase 2 — variant masks", ["phase_2/results", "phase_2/scripts", "phase_2/data"],
     "Phenotype-independent: built from the release VEP with no reference to who is a case."),
    ("Phase 3 — ancestry PCA and GRMs", ["phase_3/data", "phase_3/scripts"],
     "Phenotype-independent: ran over everyone with exome data per ancestry (51,867 EUR, "
     "14,927 AFR), not over any analysis cohort — which is why a new phenotype does not need a new "
     "PCA. The LD-pruned sets double as the GRMs. `ALL.common_ldpruned` comes from `analysis/elena`, "
     "since the replication never built a combined set; it was keyed on all 70,925 people and so "
     "carries none of the cohort defects the replication found."),
    ("Phases 4 and 5 — scripts", ["phase_4/scripts", "phase_5/scripts"],
     "Copied as a starting point, then rewritten for this cohort and for the one-call grid design "
     "(premise P10). Digests do not match where that happened, which is the expected result."),
]

tot = m = 0
for title, roots, why in GROUPS:
    w(f"## {title}\n\n{why}\n")
    rows = []
    for root in roots:
        for p in walk(HERE / root):
            rel = p.relative_to(HERE)
            src = (EL / "rarevariantExWAS/exome_ldpruned" / p.name
                   if p.name.startswith("ALL.common_ldpruned") else SRC / rel)
            if not src.exists():
                rows.append((str(rel), p.stat().st_size, "built here"))
                continue
            ok = digest(p) == digest(src)
            tot += 1
            m += ok
            st = "match" if ok else ("annotated" if p.name == "FINDINGS.md" else "rewritten")
            rows.append((str(rel), p.stat().st_size, st))
    w("| file | size | status |")
    w("|---|---:|---|")
    for r, size, st in sorted(rows):
        h = (f"{size/1e9:.2f} GB" if size > 1e9 else
             f"{size/1e6:.1f} MB" if size > 1e6 else f"{size/1e3:.0f} KB")
        w(f"| `{r}` | {h} | {st} |")
    w("")

w(f"**{m} of {tot} copied files byte-identical**, the rest `annotated` or `rewritten` as above.\n")
w("---\n")
w("## The one path that points outside this folder\n")
w("| what | where | size |")
w("|---|---|---:|")
w("| per-chromosome exome genotypes, SAIGE step 2 | "
  "`analysis/elena/rarevariant_geneburden/plink_deduplicated/` | 438 GB |")
w("\nNot copied, and copying it would make nothing safer: a mechanical deduplicated conversion of")
w("the release exome, the same class of input as `/static/PMBB/`. It encodes no decision.\n")
w("## Built here\n")
w("| | |")
w("|---|---|")
w("| `phase_1/` | the bilateral sensorineural phenotype and its cohort |")
w("| `phase_3/scripts/03_build_covariates.py` + outputs | covariates for this cohort |")
w("| `phase_4/results/`, `phase_5/` | the test, and everything read off it |")
w("| `phase_5/power_control/`, `phase_5/complement/` | the two controls on premise P1 |")
w("| `andre_notes/` | the plain-language account of each phase |")
w("| `README.md` · `PREMISES.md` · `pipeline.md` · this file | the analysis's own documents |")
w("\n---\n\n## The rule\n")
w("This folder reads from the replication and never writes to it. Re-run this script to check that")
w("it is still true.\n")

(HERE / "PROVENANCE.md").write_text("\n".join(out))
print(f"{m} of {tot} byte-identical; PROVENANCE.md has {len(out)} lines")
